# Generated by Django 5.1.3 on 2024-11-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20241122_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.TextField(default='mikh.vega@gmail.com', max_length=150),
            preserve_default=False,
        ),
    ]
